{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3listobjects.fullname" . }}
  labels:
    {{- include "s3listobjects.labels" . | nindent 4 }}
data:
  {{- range $setting, $option := .Values.config }}
  {{ $setting }}: "{{ $option }}"
  {{- end }}
{{- end }}